"""Initial tables

Revision ID: 0bad379facf2
Revises: 
Create Date: 2025-11-06 16:30:06.212828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bad379facf2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('samples',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('pscid', sa.String(length=16), nullable=False),
    sa.Column('sampling_date', sa.Date(), nullable=True),
    sa.Column('psc', sa.Enum('YES', 'NO', name='yesno'), nullable=True),
    sa.Column('cca', sa.Enum('YES', 'NO', name='yesno'), nullable=True),
    sa.Column('ibd', sa.Enum('YES', 'NO', name='yesno'), nullable=True),
    sa.Column('fibrosis', sa.Enum('HIGH', 'LOW', name='hilo'), nullable=True),
    sa.Column('bilirubin', sa.Enum('HIGH', 'LOW', name='hilo'), nullable=True),
    sa.Column('alp', sa.Enum('HIGH', 'LOW', name='hilo'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pscid', 'type')
    )
    op.create_table('variables',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('base_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('variable_id', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(length=16), nullable=False),
    sa.Column('fold_change', sa.Float(), nullable=False),
    sa.Column('log2fc', sa.Float(), nullable=True),
    sa.Column('p_value', sa.Float(), nullable=True),
    sa.Column('auc', sa.Float(), nullable=False),
    sa.Column('adj_p_value', sa.Float(), nullable=True),
    sa.Column('median_group1', sa.Float(), nullable=False),
    sa.Column('median_group2', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['variable_id'], ['variables.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variable_id', 'condition')
    )
    op.create_table('measurements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=False),
    sa.Column('variable_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ),
    sa.ForeignKeyConstraint(['variable_id'], ['variables.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sample_id', 'variable_id')
    )
    op.create_table('metabolite_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('biochemical', sa.String(), nullable=False),
    sa.Column('pubchem', sa.String(), nullable=True),
    sa.Column('hmdb', sa.String(), nullable=True),
    sa.Column('super_pathway', sa.String(), nullable=False),
    sa.Column('sub_pathway', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['base_stats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mirna_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['base_stats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('protein_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assay', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('uniprot_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['base_stats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('protein_stats')
    op.drop_table('mirna_stats')
    op.drop_table('metabolite_stats')
    op.drop_table('measurements')
    op.drop_table('base_stats')
    op.drop_table('variables')
    op.drop_table('samples')
    # ### end Alembic commands ###
