#!/bin/sh -

docker build \
	-f ../Dockerfile \
	--target frontend-update-lock \
	-t frontend-update-lock \
	--build-arg UID="$(id -u)" \
	--build-arg GID="$(id -g)" \
	. &&
docker run \
	--rm \
	frontend-update-lock >package-lock.json.new

if ! cmp -s package-lock.json.new package-lock.json
then
	mv package-lock.json.new package-lock.json
	echo 'Package lock updated'
else
	rm package-lock.json.new
	echo 'Package lock did not need updating'
fi
