#!/bin/sh -

cp package-lock.json package-lock.json.old

docker build \
	--file ../Dockerfile \
	--target frontend-dev \
	--tag frontend-update-lock \
	--build-arg UID="$(id -u)" \
	--build-arg GID="$(id -g)" \
	. &&
docker run \
	--rm \
	--volume './:/home/psc-atlas/frontend' \
	frontend-update-lock \
	npm install \
		--package-lock-only \
		--ignore-scripts \
		--no-audit \
		--fund=false

if ! cmp -s package-lock.json package-lock.json.old
then
	echo 'Package lock updated'
else
	echo 'Package lock did not need updating'
fi

rm -f package-lock.json.old
