name: psc-atlas

services:

  proxy:
    build:
      context: .
      target: proxy-prod
      args:
        UID: "${UID:-1000}"
        GID: "${GID:-1000}"
    volumes:
      - project-vol:/home/psc-atlas/vol
    ports:
      - 127.0.0.1:3320:8080

volumes:
  project-vol:
