name: psc-atlas

services:

  proxy:
    image: harbor.nbis.se/meerkats/psc-atlas:${TAG:-latest}
    build:
      context: .
      target: proxy-prod
      args:
        UID: "${UID:-1000}"
        GID: "${GID:-1000}"
    volumes:
      - project-vol:/home/psc-atlas/vol
    ports:
      - 127.0.0.1:3320:8080
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://proxy:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  project-vol:
