services:

  frontend:
    build:
      context: frontend
      dockerfile: ../Dockerfile
      target: frontend-dev
      args:
        UID: "${UID:-1000}"
        GID: "${GID:-1000}"
    volumes:
      - ./frontend:/home/psc-atlas/frontend

  backend:
    build:
      context: backend
      dockerfile: ../Dockerfile
      target: backend-dev
      args:
        UID: "${UID:-1000}"
        GID: "${GID:-1000}"
    volumes:
      - ./vol:/home/psc-atlas/vol
      - ./backend:/home/psc-atlas/backend

  proxy:
    build:
      target: proxy-dev
      args:
        UID: "${UID:-1000}"
        GID: "${GID:-1000}"
