#!/bin/sh -

docker build \
	--file ../Dockerfile \
	--target backend-dev \
	--tag backend-update-lock \
	--build-arg UID="$(id -u)" \
	--build-arg GID="$(id -g)" \
	. &&
docker run \
	--rm \
	--volume './pyproject.toml:/tmp/pyproject.toml:ro' \
	--workdir /tmp \
	backend-update-lock \
	sh -c '
		uv sync --upgrade &&
		cat uv.lock
	' >uv.lock.new

if ! cmp -s uv.lock.new uv.lock
then
	mv uv.lock.new uv.lock
		echo 'UV lock updated'
	else
		rm uv.lock.new
	echo 'UV lock did not need updating'
fi
