#!/bin/sh -

set -x

docker build \
	-f ../Dockerfile \
	--target backend-update-lock \
	-t backend-update-lock \
	--build-arg UID="$(id -u)" \
	--build-arg GID="$(id -g)" \
	. &&
docker run \
	--rm \
	backend-update-lock >uv.lock.new

if ! cmp -s uv.lock.new uv.lock
then
	mv uv.lock.new uv.lock
		echo 'UV lock updated'
	else
		rm uv.lock.new
	echo 'UV lock did not need updating'
fi
