"""Initial tables

Revision ID: 01cf41403ef0
Revises: 
Create Date: 2025-11-24 17:03:24.648163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01cf41403ef0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('condition_variable',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('measurement_variable',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sample',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('sample_id', sa.String(length=32), nullable=False),
    sa.Column('sample_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'sample_id')
    )
    op.create_table('base_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('variable_id', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(length=16), nullable=False),
    sa.Column('fold_change', sa.String(), nullable=True),
    sa.Column('log2fc', sa.String(), nullable=True),
    sa.Column('p_value', sa.String(), nullable=True),
    sa.Column('auc', sa.String(), nullable=True),
    sa.Column('adj_p_value', sa.String(), nullable=True),
    sa.Column('median_group1', sa.Float(), nullable=False),
    sa.Column('median_group2', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['variable_id'], ['measurement_variable.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variable_id', 'condition')
    )
    op.create_table('condition',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=False),
    sa.Column('condition_variable_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['condition_variable_id'], ['condition_variable.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('condition_variable_id', 'sample_id')
    )
    op.create_table('measurement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=False),
    sa.Column('measurement_variable_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['measurement_variable_id'], ['measurement_variable.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('measurement_variable_id', 'sample_id')
    )
    op.create_table('metabolite_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('biochemical', sa.String(), nullable=False),
    sa.Column('pubchem', sa.String(), nullable=True),
    sa.Column('hmdb', sa.String(), nullable=True),
    sa.Column('super_pathway', sa.String(), nullable=False),
    sa.Column('sub_pathway', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['base_stats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mirna_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['base_stats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('protein_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assay', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('uniprot_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['base_stats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('protein_stats')
    op.drop_table('mirna_stats')
    op.drop_table('metabolite_stats')
    op.drop_table('measurement')
    op.drop_table('condition')
    op.drop_table('base_stats')
    op.drop_table('sample')
    op.drop_table('measurement_variable')
    op.drop_table('condition_variable')
    # ### end Alembic commands ###
